### ISSUE TITLE
Build fails with TypeScript errors regarding Timer types and NodeList iteration in flyff.ts

### ISSUE THREAD

**Issue by s0569591** [Ariorh1337/flyff_bot#6]
### Issue Description

I am encountering a build failure in the `flyff_bot` project when trying to run `npm run build-chrome`. The TypeScript compiler throws multiple errors related to type assignments, particularly with Timer types and NodeList iteration in the `flyff.ts` file.

### Detailed Error Messages

1. **Timer Type Errors:**
   - Several errors report that the type 'number | Timer' cannot be assigned to parameters expecting 'string | number | Timeout | undefined'. This issue suggests a possible mismatch in the expected types for timers, perhaps due to conflicting definitions between browser and Node.js environments.

2. **NodeList Iteration Errors:**
   - Errors indicate that the type 'NodeListOf<Element>' must have a 'Symbol.iterator()' method that returns an iterator, implying that the TypeScript configuration or code may not be properly set up to handle NodeList objects like arrays.

### Steps to Reproduce

1. Clone the `flyff_bot` repository.
2. Run `npm install` to install dependencies.
3. Execute `npm run build-chrome` in the terminal.

Errors:

user@iMac-von-User flyff_bot % npm run build-chrome 

> flyff_universe_autohotkey@0.1.1 build-chrome
> webpack --config webpack/webpack.chrome.js

assets by status 3.42 KiB [cached] 4 assets
./src/flyff.ts 39 bytes [built] [code generated] [5 errors]

ERROR in ./src/flyff.ts
Module build failed (from ./node_modules/ts-loader/index.js):
Error: TypeScript emitted no output for /Users/user/Downloads/Bot/flyff_bot/src/flyff.ts.
    at makeSourceMapAndFinish (/Users/user/Downloads/Bot/flyff_bot/node_modules/ts-loader/dist/index.js:55:18)
    at successLoader (/Users/user/Downloads/Bot/flyff_bot/node_modules/ts-loader/dist/index.js:42:5)
    at Object.loader (/Users/user/Downloads/Bot/flyff_bot/node_modules/ts-loader/dist/index.js:23:5)

ERROR in /Users/user/Downloads/Bot/flyff_bot/src/flyff.ts
./src/flyff.ts 48:30-38
[tsl] ERROR in /Users/user/Downloads/Bot/flyff_bot/src/flyff.ts(48,31)
      TS2769: No overload matches this call.
  Overload 1 of 2, '(intervalId: string | number | Timeout | undefined): void', gave the following error.
    Argument of type 'number | Timer' is not assignable to parameter of type 'string | number | Timeout | undefined'.
      Type 'Timer' is not assignable to type 'string | number | Timeout | undefined'.
        Property '[Symbol.dispose]' is missing in type 'Timer' but required in type 'Timeout'.
  Overload 2 of 2, '(id: number | undefined): void', gave the following error.
    Argument of type 'number | Timer' is not assignable to parameter of type 'number | undefined'.
      Type 'Timer' is not assignable to type 'number'.

ERROR in /Users/user/Downloads/Bot/flyff_bot/src/flyff.ts
./src/flyff.ts 123:30-38
[tsl] ERROR in /Users/user/Downloads/Bot/flyff_bot/src/flyff.ts(123,31)
      TS2769: No overload matches this call.
  Overload 1 of 2, '(intervalId: string | number | Timeout | undefined): void', gave the following error.
    Argument of type 'number | Timer' is not assignable to parameter of type 'string | number | Timeout | undefined'.
  Overload 2 of 2, '(id: number | undefined): void', gave the following error.
    Argument of type 'number | Timer' is not assignable to parameter of type 'number | undefined'.

ERROR in /Users/user/Downloads/Bot/flyff_bot/src/flyff.ts
./src/flyff.ts 274:30-38
[tsl] ERROR in /Users/user/Downloads/Bot/flyff_bot/src/flyff.ts(274,31)
      TS2769: No overload matches this call.
  Overload 1 of 2, '(intervalId: string | number | Timeout | undefined): void', gave the following error.
    Argument of type 'number | Timer' is not assignable to parameter of type 'string | number | Timeout | undefined'.
  Overload 2 of 2, '(id: number | undefined): void', gave the following error.
    Argument of type 'number | Timer' is not assignable to parameter of type 'number | undefined'.

ERROR in /Users/user/Downloads/Bot/flyff_bot/src/flyff.ts
./src/flyff.ts 311:15-79
[tsl] ERROR in /Users/user/Downloads/Bot/flyff_bot/src/flyff.ts(311,16)
      TS2488: Type 'NodeListOf<Element>' must have a 'Symbol.iterator()' method that returns an iterator.

ERROR in /Users/user/Downloads/Bot/flyff_bot/src/flyff.ts
./src/flyff.ts 315:12-70
[tsl] ERROR in /Users/user/Downloads/Bot/flyff_bot/src/flyff.ts(315,13)
      TS2488: Type 'NodeListOf<Element>' must have a 'Symbol.iterator()' method that returns an iterator.

5 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.91.0 compiled with 6 errors in 1484 ms

**Comment by Ariorh1337** [comment]
Can't reproduce, but i made a fix which used "Number" instead of "NodeJS.Timer"
Should work fine

**Comment by lrphael** [comment]
Did you push it @Ariorh1337 ? I still have the same problem with the const interval. I change the type too.

**Comment by Ariorh1337** [comment]
> Did you push it @Ariorh1337 ? I still have the same problem with the const interval. I change the type too.

Yes, should be there, could you add the error?

**Comment by lrphael** [comment]
> > Did you push it @Ariorh1337 ? I still have the same problem with the const interval. I change the type too.
> 
> Yes, should be there, could you add the error?

I opened a pull request here on your github, in it you can see how I'm treating the Timer error in the interval variable.

**Comment by Ariorh1337** [comment]
When setting up the repository, I forgot to indicate that the browser environment was used. fixed
